const  useRouter  = require("./user")
const productRouter = require("./product")
const authorsRouter = require("./author")
const BannerRouter = require("./banner")
const ProductCategoryRouter = require("./productcategory")
const newsCategoryRouter = require("./newscategory")
const newsRouter = require("./news")
const PublisherRouter = require("./publisher")
const CouponRouter = require("./coupon")
const OrderRouter = require("./order")
const BookCategory = require("./bookcategory")
const {notFound ,errHandler}= require("../middlewares/errorhandler")
const payment = require("./payments")
const initrouter = (app) => {
    app.use('/api/user',useRouter)
    app.use('/api/product',productRouter)
    app.use('/api/author',authorsRouter)
    app.use('/api/banner',BannerRouter)
    app.use('/api/productcategory',ProductCategoryRouter)
    app.use('/api/newscategory',newsCategoryRouter)
    app.use('/api/news',newsRouter)
    app.use('/api/publisher',PublisherRouter)
    app.use('/api/coupon', CouponRouter)
    app.use('/api/order', OrderRouter )
    app.use('/api/bookcategory', BookCategory )
    app.use('api/payment', payment)
    app.use(notFound)
    app.use(errHandler)
}

module.exports = initrouter;